/**
 * Generates the Alexa+ store-listing media from assets/icon.svg:
 *   - light icons in the six required sizes (72, 64, 88, 126, 180, 241)
 *   - a 600×900 carousel image
 * Output: assets/generated/ (git-ignored; referenced from addon-package/addon.json).
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const out = path.join(root, 'assets', 'generated');
await mkdir(out, { recursive: true });
const svg = await readFile(path.join(root, 'assets', 'icon.svg'));

for (const size of [72, 64, 88, 126, 180, 241]) {
  await sharp(svg).resize(size, size).png().toFile(path.join(out, `icon-${size}.png`));
}

// Carousel: brand tile on a soft background with the product line underneath.
const carousel = Buffer.from(`
<svg xmlns="http://www.w3.org/2000/svg" width="600" height="900">
  <rect width="600" height="900" fill="#0f1a33"/>
  <rect x="0" y="0" width="600" height="900" fill="url(#bg)"/>
  <defs>
    <radialGradient id="bg" cx="0.5" cy="0.35" r="0.8">
      <stop offset="0" stop-color="#1f3f7a"/><stop offset="1" stop-color="#0f1a33"/>
    </radialGradient>
  </defs>
  <g transform="translate(150 190) scale(0.585)">${svg.toString().replace(/<\?xml[^>]*>/, '').replace(/<svg[^>]*>/, '').replace('</svg>', '')}</g>
  <text x="300" y="560" text-anchor="middle" font-family="Helvetica, Arial, sans-serif" font-size="64" font-weight="700" fill="#ffffff">Custodian</text>
  <text x="300" y="620" text-anchor="middle" font-family="Helvetica, Arial, sans-serif" font-size="28" fill="#b9c7e6">Recall &amp; maintenance watch</text>
  <text x="300" y="660" text-anchor="middle" font-family="Helvetica, Arial, sans-serif" font-size="28" fill="#b9c7e6">for everything you own</text>
  <text x="300" y="790" text-anchor="middle" font-family="Helvetica, Arial, sans-serif" font-size="24" fill="#7f93bf">“Alexa, is anything in my house recalled?”</text>
</svg>`);
await sharp(carousel).png().toFile(path.join(out, 'carousel-600x900.png'));
await writeFile(path.join(out, 'README.txt'), 'Generated by scripts/gen-assets.ts — do not edit by hand.\n');
console.log(`wrote icons + carousel to ${out}`);
